# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=4, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField()),
                ('salario', models.FloatField()),
                ('comentarios', models.CharField(max_length=1000)),
                ('activo', models.IntegerField(default=1)),
                ('fecha_ultima_actividad', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
