# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ultima_actividad',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
